### ISSUE TITLE
Include positive controls in results

### ISSUE THREAD

**Issue by Kim-Macdonald** [BCCDC-PHL/pangolin-nf#12]
Request to include the positives in the pangolin pipeline results (for positive control QC - ensure they aren't a different lineage than expected). 

Negatives probably not important since we monitor % completeness for those.  

This will also allow John/end users to check positives in our merged output file with updated lineages.

**Comment by dfornika** [comment]
Just adding a note for myself. this is where the change needs to be made:

https://github.com/BCCDC-PHL/pangolin-nf/blob/a83067bd5d7bf3d07cc2631ae183a013b3e99db1/modules/pangolin.nf#L85-L86
